live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x676767"
blue = "0xa6aaf1"
cyan = "0x5ffdff"
green = "0x57e690"
magenta = "0xe07de0"
red = "0xdc7974"
white = "0xfeffff"
yellow = "0xece100"

[colors.cursor]
cursor = "0xfefffe"
text = "0x000000"

[colors.normal]
black = "0x14191e"
blue = "0x2743c7"
cyan = "0x00c5c7"
green = "0x00c200"
magenta = "0xbf3fbd"
red = "0xb43c29"
white = "0xc7c7c7"
yellow = "0xc7c400"

[colors.primary]
background = "0x14191e"
foreground = "0xdbdbdb"

[colors.selection]
background = "0xb3d7ff"
text = "0x000000"

[cursor]
style = "Block"
unfocused_hollow = false

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"
family = "JetBrainsMono Nerd Font"


[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Regular Italic"
family = "JetBrainsMono Nerd Font"

[font.normal]
style = "Regular"
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "FullScreen"

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 2
y = 2
